app/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from carts.views import carts_app
from dishes.views import dish_list

urlpatterns = [
    url(r"^$", dish_list, name="index"),
    url(r"^dishes/", include(("dishes.urls", "dishes"), namespace="dishes")),
    url(r"^carts/$", carts_app, name="carts"),
    url(r"^api/carts/", include(("carts.api.urls", "carts_api"), namespace="carts-api")),
    url(r"^admin/", admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/api/urls.py
from django.conf.urls import url
from rest_framework import routers

from . import views

router = routers.DefaultRouter()

urlpatterns = [
    url(r"^$", views.CartListAPIView.as_view(), name="list"),
    url(r"^create/$", views.CartCreateAPIView.as_view(), name="create"),
    url(r"^update/(?P<pk>\d+)/$", views.CartUpdateAPIView.as_view(), name="update"),
    url(r"^delete/(?P<pk>\d+)/$", views.CartDeleteAPIView.as_view(), name="delete"),
    url(
        r"^set-as-current/(?P<pk>\d+)/$",
        views.SetAsCurrentAPIView.as_view(),
        name="set-as-current",
    ),
    url(r"^current/$", views.CurrentCartAPIView.as_view(), name="current"),
    url(
        r"^add-to-cart/(?P<dish_id>\d+)/(?P<quantity>\d+)/$",
        views.AddToCartAPIView.as_view(),
        name="add-to-cart",
    ),
    url(
        r"^remove-from-cart/(?P<pk>\d+)/(?P<dish_id>\d+)/$",
        views.RemoveItemFromCartAPIView.as_view(),
        name="remove-from-cart",
    ),
    url(r"^(?P<pk>\d+)/$", views.CartDetailAPIView.as_view(), name="detail"),
]

dishes/urls.py
from django.conf.urls import url

from .views import dish_detail, dish_list

urlpatterns = [
    url(r"^category/(?P<category_slug>[^/]+)/$", dish_list, name="list"),
    url(r"^(?P<slug>[^/]+)/$", dish_detail, name="detail"),
]

dishes/models.py
from django.urls import reverse
from django.db import models
from django.utils import timezone

from app.models import TimeStampMixin


class Category(models.Model):
    name = models.CharField(max_length=256, verbose_name="Name")
    slug = models.SlugField(unique=True, verbose_name="Slug for category")

    def get_absolute_url(self):
        return reverse("dishes:list", kwargs={"category_slug": self.slug})

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return "Category %s" % self.name


def upload_location(instance, filename):
    return "dishes/%s" % (filename)


class Dish(TimeStampMixin):
    name = models.CharField(max_length=128, verbose_name="Name")
    description = models.TextField()
    image = models.ImageField(
        upload_to=upload_location,
        width_field="width_field",
        height_field="height_field",
        verbose_name="Image",
    )
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    preparing_time = models.DurationField(default=timezone.timedelta(minutes=5))
    for_vegan = models.BooleanField(default=False)
    slug = models.SlugField(unique=True, verbose_name="Slug for dish")
    category = models.ForeignKey(Category, on_delete=models.PROTECT)

    def get_absolute_url(self):
        return reverse("dishes:detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Dish"
        verbose_name_plural = "Dishes"
        ordering = ["-created_at"]

dishes/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, render

from dishes.models import Category, Dish


def dish_list(request, category_slug=None):
    if category_slug is None:
        dishes = Dish.objects.all()
    else:
        category = get_object_or_404(Category, slug=category_slug)
        dishes = Dish.objects.filter(category=category)
    sort_param_name = "sort"
    sort = request.GET.get(sort_param_name)
    if sort == "asc":
        dishes = dishes.order_by("name")
    elif sort == "desc":
        dishes = dishes.order_by("-name")
    paginator = Paginator(dishes, 6)
    page_param_name = "page"
    page = request.GET.get(page_param_name)
    try:
        dishes = paginator.page(page)
    except PageNotAnInteger:
        dishes = paginator.page(1)
    except EmptyPage:
        dishes = paginator.page(paginator.num_pages)
    context = {
        "page_param_name": page_param_name,
        "dishes": dishes,
        "sort_param_name": sort_param_name,
        "sort": sort,
    }
    return render(request, "index.html", context)


def dish_detail(request, slug=None):
    dish = get_object_or_404(Dish, slug=slug)
    context = {
        "dish": dish,
    }
    return render(request, "dish_detail.html", context)

templates/cart_create.html
{% extends 'index.html' %}

{% block content %}

<h1>Creating of new cart</h1>

<form action="" method="POST"> {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create cart" />
</form>

{% endblock content %}

templates/carts_app.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Carts</title>
  <link rel="stylesheet" href="{% static 'static/css/main.c17080f1.css' %}">
  <link rel="shortcut icon" href="{% static 'static/favicon.ico' %}" type="image/x-icon">
</head>
<body>
  <noscript>
    You need to enable JavaScript to run this app.
  </noscript>
  <div id="root"></div>
  <script src="{% static 'static/js/main.cc499d2e.js' %}"></script>
</body>
</html>

templates/dish.html
{% extends 'index.html' %}

{% block content %}

<div class="card mb-3">
  <img src="{{dish.image.url}}" alt="{{dish.name}}">
  <div class="card-body">
    <h1 class="card-title">
      {{ dish.name }}
      <span class="badge badge-info">${{ dish.price }}</span>
    </h1>
    <p class="card-text">{{ dish.description }}</p>
    <p class="card-text"><small class="text-muted">Last updated {{ dish.updated_at }}</small></p>
    <p class="card-text"><small class="text-muted">Added {{ dish.created_at }}</small></p>
    <span class="badge badge-pill badge-primary">{{ dish.category.name }}</span>
    {% if dish.for_vegan %}
    <span class="badge badge-pill badge-success">For vegans!</span>
    {% endif %}
  </div>
</div>

{% endblock content %}

templates/dish_detail.html
{% extends 'index.html' %}

{% block content %}

<div class="media">
  <div class="mr-3">
    <div class="product__cover" style="background-image: url('{{dish.image.url}}')" alt="{{dish.name}}"></div>
    <div>
      {% if dish.for_vegan %}
      <div class="badge badge-pill badge-success">For vegans!</div>
      {% endif %}
      <div class="badge badge-pill badge-primary">{{ dish.category.name }}</div>
    </div>
  </div>
  <div class="media-body">
    <h1 class="card-title">
      {{ dish.name }}
      <span class="badge badge-warning">${{ dish.price }}</span>
    </h1>
    <p class="card-text">
      {{ dish.description }}
    </p>
    <p>
      PREPARING TIME: {{ dish.preparing_time }}
    </p>
    <button data-url class="btn btn-primary cart-add">Add to cart</button>
    <div>
      <small class="text-muted">Last updated {{ dish.updated_at }}</small>
    </div>
    <div>
      <small class="text-muted">Added {{ dish.created_at }}</small>
    </div>
  </div>
</div>

{% endblock content %}

templates/index.html
{% load static %}
{% load categories %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Food Menu | Healthy and tasty food!</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body style>
  <nav class="navbar navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="/">Menu</a>
      <a class="Cart my-2 my-lg-0" href="{% url 'carts' %}">
        <div class="cart">
          <img class="cart__img" src="{% static 'img/cart.png' %}" alt="">
          <div class="cart__info">
            <div class="cart__name"></div>
            <div class="cart__Count">
              Items count:
              <span class="cart__count"></span>
              ($<span class="cart__sum"></span>)
            </div>
          </div>

        </div>
      </a>
    </div>
  </nav>

  <div class="container">
    <div class="row no-gutters">
      <nav class="col-2 d-none d-sm-block bg-light sidebar pt-2">
        <ul class="nav nav-pills flex-column">
          {% get_categories as categories %}
          {% for category in categories %}
          <li class="nav-item">
            <a class="nav-link" href="{{ category.get_absolute_url }}">
              {{ category.name }}
            </a>
          </li>
          {% endfor %}
        </ul>
      </nav>

      <main class="col-sm-9 ml-sm-auto col-md-10" role="main">
      {% block content %} <!-- BLOCK CONTENT -->
      <h1>Menu
        <!-- asc desc reset current page -->
        <a href="?page=1&sort=asc">Asc</a>
        <a href="?page=1&sort=desc">Desc</a>
      </h1>
      <div class="row text-center placeholders">
        {% for dish in dishes %}
        <div class="product col-4 placeholder mb-4">
          <div class="card">
            <a href="{{ dish.get_absolute_url }}">
              <div class="product__img" style="background-image: url('{{ dish.image.url }}')"></div>
            </a>
            <div class="card-body">
              <h4 class="card-title">{{ dish.name }}</h4>
              <button data-url="{% url 'carts-api:add-to-cart' dish_id=dish.id quantity=1 %}" class="btn btn-primary cart-add">Add to cart</button>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% include 'paginator.html' with page=dishes sort=sort %}

      {% endblock content %} <!-- ENDBLOCK CONTENT -->
      </main>

    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  <script src="{% static 'js/app.js' %}"></script>
  </body>
</html>

templates/paginator.html
{% if page.has_other_pages %}
  <nav aria-label="page navigation">
    <ul class="pagination">
      {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?{{ page_param_name }}={{ page.previous_page_number }}&{{ sort_param_name }}={{ sort }}">Prev</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <span class="page-link">Prev</span>
      </li>
      {% endif %}

      {% for page_num in page.paginator.page_range %}
        {% if page.number == page_num %}
        <li class="page-item active">
          <a class="page-link" href="?{{ page_param_name }}={{ page_num }}&{{ sort_param_name }}={{ sort }}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="?{{ page_param_name }}={{ page_num }}&{{ sort_param_name }}={{ sort }}">{{ page_num }}</a>
        </li>
        {% endif %}
      {% endfor %}
      {% if page.has_next %}
      <li class="page-item">
        <a class="page-link" href="?{{ page_param_name }}={{ page.next_page_number }}&{{ sort_param_name }}={{ sort }}">Next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <span class="page-link">Next</span>
      </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}